{% set name = "pypolyagamma" %}
{% set version = "1.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da2ab9459a82dfbf2be26bb5cb8a41aed57515bf64b8d981136f96953f6f44cb

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython <0.29
    - llvm-openmp  # [osx]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - llvm-openmp  # [osx]

test:
  imports:
    - pypolyagamma

about:
  home: https://github.com/slinderman/pypolyagamma
  license: MIT
  summary: A port of Jesse Windles PolyaGamma sampling code using Cython.

extra:
  recipe-maintainers:
    - slinderman
    - beckermr
