{% set name = "pypolyagamma" %}
{% set version = "1.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/slinderman/pypolyagamma/archive/{{ version }}.tar.gz
  sha256: c98828ad630586c516a4e69698914d1132682eb39d48822fd804b7163eecee83

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython
    {% if not compiler('c').startswith('toolchain') %}
    - llvm-openmp  # [osx]
    {% endif %}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    {% if not compiler('c').startswith('toolchain') %}
    - llvm-openmp  # [osx]
    {% endif %}

test:
  imports:
    - pypolyagamma

about:
  home: https://github.com/slinderman/pypolyagamma
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A port of Jesse Windles PolyaGamma sampling code using Cython.

extra:
  recipe-maintainers:
    - slinderman
    - beckermr
