{% set name = "pypolyagamma" %}
{% set version = "0.2.1" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/slinderman/pypolyagamma/archive/{{ version }}.tar.gz
    sha256: 57cbf8e12aafa137940c3a693b873c53037fa80cd5d2a8b1a6709d102e718452

build:
    number: 2
    skip: True  # [win]

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
        - setuptools
        - numpy
        - cython
        - gsl
        - openblas
    run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy
        - gsl
        - openblas

test:
    imports:
        - pypolyagamma

about:
    home: https://github.com/slinderman/pypolyagamma
    license: MIT
    summary: A port of Jesse Windles PolyaGamma sampling code using Cython.

extra:
    recipe-maintainers:
        - slinderman
        - mmb90
