{% set name = "pypolyagamma" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: afef0244a854754675d2056f6aba09923685983f07ab50357427ae26388d7ac7

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    {% if not compiler('c').startswith('toolchain') %}
    - llvm-openmp  # [osx]
    {% endif %}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    {% if not compiler('c').startswith('toolchain') %}
    - llvm-openmp  # [osx]
    {% endif %}

test:
  imports:
    - pypolyagamma

about:
  home: https://github.com/slinderman/pypolyagamma
  license: GPL-3
  license_family: GPL
  summary: A port of Jesse Windles PolyaGamma sampling code using Cython.

extra:
  recipe-maintainers:
    - slinderman
    - beckermr
