compiler_stack: comp7
max_py_ver: '37'
travis:
  secure:
    BINSTAR_TOKEN: qG6SYGJLP+gjCADHimqPsHsJkQB/bwt70nSx2RlgtZXPZWaxZVS9gYoJYc18kC+d6jcqSXbzy3qbCeZnCyULgYBwByGPP5fk6Vtud15e1lixEskddj61c7Qn05193LlubICTNsqPwF/3lV6ISf9wkCcwDYBqRJ6/KoLgVugFChGDuTu8sV/9VITWS76upsrlc+MhDKHo3gp2uHUkxcBZiW71fQC3LqG49PvzL0MSxr4B9VWuZtA0l7EOhjiD4Hbgn7mMXnD2JAdIm98hGZ0QZLpEOW8uBG9a9mdHQeiFEjw+Awkj1hKxnuEw2NFfkTuCD5JwyiLgQcizhbfDCMlNC00+l4dagslZAIPJtK2hixr/sxMaTxl7ux8Db8pxbBMY83lOVcVUkWiI4buKMdzCbayRmRxX+XXExIuNbfnvNJEujQFsVM+xBp3ajEwNHqt9LbBNo+9/9HioLfHwiVurLvf2odhBDbwk9blfLYdgjrdI/oH11aBqgDGo+av8IJJeeazQ/QVpt4WgS41piMPzYGUji9I09W1eJ/EpiwSVRt5txCZc2gSJPhOXNLr8dEA6Z2Roe8xNORqdPOvWrVFOHknVJHIjbJk0ZoH8HhSdtcckK+7Y+RN5Yx9X2UfpJ9d4E0M1cTRgaOHZd1/CRdAidqo3MhY3F+uPzRaaQt86ojk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
