travis:
  secure:
    BINSTAR_TOKEN: qfdYbZWLyW2y4eQdF6UVs0kmrFnoE2Q6JRN1Hm4rkak02SnM/uV9rRmgS3tqXo/cmJn0YtIs7guhaFetG+t1UEUnVAvg8PkcjsO5lMEWod3eWh8aRmrqZpDOabck4ak6ReQaT8P/KiCbF8UT1Xg2B/j3P27m0tJ0FBOnS5HAZ7c8jZlLlsR+4yskmwcPoJxQmmXrlcC0R4k5Je4MlFodsjRZVMrXOA9Dps8PDlm1oVxq3trfDENGGienp0dcAvmQp8oTayAQLAehE+acPBB2NjwpxivySzni/M4FDK3WvusD9idAJ3N+DiLbzrhxdxx2l10b52dlbo6OQKsspnP+Z3yW0RiP0d1nqD2pXAIY0X3+l3G/o2HdNQI7BHUYZ1l+Ac8JmmvT+Uoilz0KeSzHKfQNxaak6Tc/Vzu8AHYAQftKABCl81nKtGyS/AFa9RkXkKS1QbD7e6//IlqyioPDitE1l7Cn5ZwYHoerhbw9TwXtqBMucNzNhtoV//HFp5wG/QhUIxdUUjNuu33zDX3SWRMTKcxRbavNFw+GSA8bQmmbjlZruI73oZdyeWfZ4RgCszst72dPt5rxpGFqNCkXQ1UTT+qImyz4Z6eDcKoWnMuMoKXab5sWo5RZnQs0H45UKGEL8zio7TcjhTOmGS+WGEGw0Su9LcfhMmGCT4TGceE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
